from flask import Flask, render_template, request, jsonify, send_file
from flask_cors import CORS
import json
import io
import os

app = Flask(__name__)
CORS(app)

# Store database schema in memory
database_schema = {
    "tables": []
}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/tables', methods=['GET'])
def get_tables():
    return jsonify(database_schema)

@app.route('/api/sync', methods=['POST'])
def sync_tables():
    data = request.json
    if 'tables' in data:
        database_schema['tables'] = data['tables']
    return jsonify({"success": True})

@app.route('/api/tables', methods=['POST'])
def add_table():
    data = request.json
    table = {
        "id": data.get("id", len(database_schema["tables"]) + 1),
        "name": data.get("name", "new_table"),
        "x": data.get("x", 100),
        "y": data.get("y", 100),
        "columns": data.get("columns", [
            {"name": "id", "type": "INTEGER", "primary": True, "autoincrement": True, "nullable": False}
        ]),
        "rows": data.get("rows", [])
    }
    database_schema["tables"].append(table)
    return jsonify(table)

@app.route('/api/tables/<int:table_id>', methods=['PUT'])
def update_table(table_id):
    data = request.json
    for table in database_schema["tables"]:
        if table["id"] == table_id:
            table.update(data)
            return jsonify(table)
    return jsonify({"error": "Table not found"}), 404

@app.route('/api/tables/<int:table_id>', methods=['DELETE'])
def delete_table(table_id):
    database_schema["tables"] = [t for t in database_schema["tables"] if t["id"] != table_id]
    return jsonify({"success": True})

@app.route('/api/export/<format>', methods=['GET'])
def export_schema(format):
    if format == 'sql':
        return export_sql()
    elif format == 'json':
        return export_json()
    elif format == 'mysql':
        return export_mysql()
    elif format == 'postgresql':
        return export_postgresql()
    return jsonify({"error": "Unknown format"}), 400

def export_sql():
    sql = "-- SQLite Database Schema\n-- Generated by DB Designer\n\n"
    
    for table in database_schema["tables"]:
        sql += f"CREATE TABLE {table['name']} (\n"
        columns = []
        for col in table["columns"]:
            col_def = f"    {col['name']} {col['type']}"
            if col.get("primary"):
                col_def += " PRIMARY KEY"
            if col.get("autoincrement"):
                col_def += " AUTOINCREMENT"
            if not col.get("nullable", True):
                col_def += " NOT NULL"
            if col.get("default"):
                col_def += f" DEFAULT {col['default']}"
            columns.append(col_def)
        sql += ",\n".join(columns)
        sql += "\n);\n\n"
    
    return send_file(
        io.BytesIO(sql.encode()),
        mimetype='text/plain',
        as_attachment=True,
        download_name='schema.sql'
    )

def export_mysql():
    sql = "-- MySQL Database Schema\n-- Generated by DB Designer\n\n"
    
    for table in database_schema["tables"]:
        sql += f"CREATE TABLE `{table['name']}` (\n"
        columns = []
        primary_keys = []
        for col in table["columns"]:
            col_def = f"    `{col['name']}` {col['type']}"
            if col.get("primary"):
                primary_keys.append(col['name'])
            if not col.get("nullable", True):
                col_def += " NOT NULL"
            if col.get("autoincrement"):
                col_def += " AUTO_INCREMENT"
            if col.get("default"):
                col_def += f" DEFAULT {col['default']}"
            columns.append(col_def)
        if primary_keys:
            columns.append(f"    PRIMARY KEY ({', '.join([f'`{pk}`' for pk in primary_keys])})")
        sql += ",\n".join(columns)
        sql += "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n"
    
    return send_file(
        io.BytesIO(sql.encode()),
        mimetype='text/plain',
        as_attachment=True,
        download_name='schema_mysql.sql'
    )

def export_postgresql():
    sql = "-- PostgreSQL Database Schema\n-- Generated by DB Designer\n\n"
    
    for table in database_schema["tables"]:
        sql += f"CREATE TABLE {table['name']} (\n"
        columns = []
        for col in table["columns"]:
            col_type = col['type']
            if col.get("autoincrement") and col_type == "INTEGER":
                col_type = "SERIAL"
            col_def = f"    {col['name']} {col_type}"
            if col.get("primary") and col_type != "SERIAL":
                col_def += " PRIMARY KEY"
            if not col.get("nullable", True) and col_type != "SERIAL":
                col_def += " NOT NULL"
            if col.get("default") and col_type != "SERIAL":
                col_def += f" DEFAULT {col['default']}"
            columns.append(col_def)
        sql += ",\n".join(columns)
        sql += "\n);\n\n"
    
    return send_file(
        io.BytesIO(sql.encode()),
        mimetype='text/plain',
        as_attachment=True,
        download_name='schema_postgresql.sql'
    )

def export_json():
    return send_file(
        io.BytesIO(json.dumps(database_schema, indent=2, ensure_ascii=False).encode()),
        mimetype='application/json',
        as_attachment=True,
        download_name='schema.json'
    )

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(debug=False, host='0.0.0.0', port=port)
